version: '2'
services:
  simple_spring_angular_app-app:
    image: simple_spring_angular_app
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://simple_spring_angular_app-postgresql:5432/simple_spring_angular_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  simple_spring_angular_app-postgresql:
    extends:
      file: postgresql.yml
      service: simple_spring_angular_app-postgresql
